export const BRIGHTNESS_THRESHOLD = 128;
export const RED_LUMINANCE_WEIGHT = 299;
export const GREEN_LUMINANCE_WEIGHT = 587;
export const BLUE_LUMINANCE_WEIGHT = 114;
export const LUMINANCE_DIVISOR = 1000;
